### ISSUE TITLE
Add country whitelist option

### ISSUE THREAD

**Issue by benkeen** [benkeen/country-region-selector#11]
It would be helpful in some cases to only show a subset of the list of countries. Add a whitelist option to let users choose exactly which countries should be included in the country dropdown.

**Comment by micbenner** [comment]
Just to be a pest, any chance of this happening anytime soon?

**Comment by benkeen** [comment]
haha not at all. :) It would be super helpful, I agree. Let me see if I can look at this week. Should be pretty straightforward to implement, I think.

**Comment by benkeen** [comment]
Added in 0.2.0
