### ISSUE TITLE
Bad region name for Sor-Trondelag in Norway

### ISSUE THREAD

**Issue by anjdreas** [benkeen/country-region-selector#16]
I don't see what is wrong, but try to select Norway, then Sor-Trondelag.

It reads `Sor-` instead of `Sor-Trondelag` for whatever reason. The source code looks good and I can't spot the culprit, but something caps it. Any idea?

**Comment by benkeen** [comment]
Sorry for the wait! I'll try to look at this tonight.

**Comment by benkeen** [comment]
Yeah, guess it's the '-' char. I retyped it in and re-generated the JS file and all seems well. Bizarre! I'll roll a new version now.
