### ISSUE TITLE
data-default-value in region

### ISSUE THREAD

**Issue by kodeine** [benkeen/country-region-selector#17]
data-default-value in region does not work.
Can you please help.

**Country Field**
```html
<select class="form-control crs-country" id="cube-wad__adr_country" label="Country" name="wad__adr_country" data-region-id="wad__adr_country" data-default-value="United States" data-default-option="...Choose" data-crs-loaded="true">
```
this field is pre-populated but not the region.

**Region Field**
```html
<select class="form-control" id="wad__adr_country" label="State" name="wad__adr_state" required="" data-value="abbr" data-default-value="DC" data-blank-option="...Select Country">
```

Thank you for this library.

**Comment by benkeen** [comment]
Huh! I'll take a look at this tonight, thanks @kodeine.

**Comment by kodeine** [comment]
Since i had customized the crs to support abbreviations for regions. I had to modify this little function to support default region values.

```
    var _setDefaultRegionValue = function(field, data, val) {
        /*console.log(field);
        console.log(data);
        console.log(val);*/
        for (var i=0; i<data.length; i++) {
            var split = data[i].split("~");
            /*console.log(split[1]);
            console.log(data[i]);
            console.log(val);*/
            //console.log(split[0]);
            //console.log(split[0] +'==='+ val);
            //console.log(split[1] +'==='+ val);
            if (split[0] === val || split[1] === val) {
                field.selectedIndex = i+1;
                break;
            }
        }
    };
```

**Comment by benkeen** [comment]
Hey @kodeine, sorry for the wait! 

I looked into this and actually the problem lies in the `data-default-value` attribute. It should read: `data-default-value="District of Columbia"` and not `data-default-value="DC"`. Basically it just uses the value="X" attributes of the region select element to figure out which one should be defaulted to. 

Hope this helps! :)

**Comment by kodeine** [comment]
Aha, so when do you plan to update the library to support region abbreviations.

**Comment by benkeen** [comment]
Unfortunately it's a fair bit of work tracking down and adding all region abbreviations for all countries. I've had a couple of contributors adding some regions, but there are still a lot more to do. So it could be some time!
