### ISSUE TITLE
is there's a way to remove default option? I dont want to show a blank option.

### ISSUE THREAD

**Issue by topasi** [benkeen/country-region-selector#20]

**Comment by benkeen** [comment]
Huh, you're right. I'm surprised that's not an option. 

This is pretty straightforward to add so I'll try to roll a new version tonight.

**Comment by benkeen** [comment]
I just release 0.1.9 that includes a new data-show-default-option="false" option.
https://github.com/benkeen/country-region-selector/releases/tag/0.1.9

**Comment by benkeen** [comment]
I'll update the docs later today.
