### ISSUE TITLE
Sporadic issue - jquery.crs.js not running 80% of the time in a large project

### ISSUE THREAD

**Issue by yaohongkok** [benkeen/country-region-selector#27]
I am making some modification on a large website which downloads a lot of JS file. This may have resulted in sporadic failure. To be explicit, the failure is the "select" tag with class "crs-country" is not populated at all. Digging into the issue, I found that the "_init" function is not being called every time.

I have found a workaround myself, namely to do the following:
    1. Comment out: Line 9 to 21 and  Line 469 to Line 474.
    2. Comment out: Line 467 ==> "$(_init)" and replace it with "$( document ).ready(_init);"

This seems to have resolved my issue.

**Comment by benkeen** [comment]
Hmm, strange! The second point shouldn't be necessary: those two are identical (See http://api.jquery.com/ready/). 

In case you don't want to modify the source code, you can also just run the init() function whenever you want, like on DOM ready. See this section: https://github.com/benkeen/country-region-selector#plain-vanilla-js-example

That allows you to ensure the select fields are always initialized.
