### ISSUE TITLE
South Africa province wrong

### ISSUE THREAD

**Issue by JoshZA** [benkeen/country-region-selector#29]
In the country data
`` ["South Africa","ZA","Eastern Cape~EC|Free State~FS|Gauteng~GT|KwaZulu-Natal~NL|Limpopo~LP|Mpumalanga~MP|Northern~Cape~NC|North West~NW|Western Cape~WC"],
``

``Northern~Cape~NC`` should be ``Northern Cape~NC``

**Comment by benkeen** [comment]
Thanks, @JoshZA. Will update now. It'll be in the next release.
