### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by dgilperez** [benkeen/country-region-selector#3]
Hi!

Thanks for stepping ahead to fill an obvious gap in the JS environment and building a fast and reliable country-region selector. 

I'd need to be able to use the selector in an internationalized web app, and present the user with the country and region names according to their desired locale. 

Are you planning to add this to country-region-selector? Any hints to do that myself?

Thanks!

**Comment by benkeen** [comment]
Hi @dgilperez, great idea!

Technically this should be pretty straightforward - just move the strings to a separate file, then add a loader (or just create multiple pre-bundled versions of the code). The bigger challenge is the actual work of doing the translations. I don't suppose you'd be able to supply a translation? If so, I could update the code to support it.

**Comment by dgilperez** [comment]
Hi @benkeen !

I ended up myself using a hand-made solution using https://github.com/hexorx/countries Rails gem. That library comes with a country selector helper, and also you can have the region information for a given country, with translations to several languages. In my solution I populate the region selector using an AJAX call on country change. I'd rather have used something speedier, like your approach, but to be honest I won't be using it myself in the next future. 

I still think this a good idea for your library, so I suggest you grab the region information for any locale you want to add (spanish would be nice ;)) from the gem I mentioned above. 

Cheers!

**Comment by sventech** [comment]
Here is a JavaScript data source that is maintained:
https://github.com/mledoze/countries

Also, this free database:
https://github.com/openmundi/world.db

Perhaps a separate translations file could be generated for each language. Then one could include the crs file and translations file, perhaps specify the translation language in a `data-translation=` or something.

**Comment by dgilperez** [comment]
Thanks a lot! Interesting references in deed!
