### ISSUE TITLE
Istanbul not delimited

### ISSUE THREAD

**Issue by futuresonus** [benkeen/country-region-selector#35]
In the list of "states" for Turkey, Istanbul is combined with the following list item, like so:
`IstanbKahramanmaras `

**Comment by benkeen** [comment]
Thanks @futuresonus! I'll fix this in the next release.

**Comment by benkeen** [comment]
Fixed here: https://github.com/benkeen/country-region-data/commit/e2f896d68e172d8d5407d3d41c1aa3c11659eec4

Will be in next release.
