### ISSUE TITLE
Build error occur , when creating customBuild with countries that have comma in their names 

### ISSUE THREAD

**Issue by alexdruk** [benkeen/country-region-selector#36]
See example below:
![screen shot 2016-05-12 at 17 28 10](https://cloud.githubusercontent.com/assets/840087/15220216/f82a81c2-1866-11e6-8cc4-678593a146a4.png)

**Comment by benkeen** [comment]
Thanks Alex! I'll take a look.

**Comment by benkeen** [comment]
Sorry - evening filled up. Will get to this soon.
