### ISSUE TITLE
Pre built javascript file Error

### ISSUE THREAD

**Issue by mukraskazungu** [benkeen/country-region-selector#39]
WARNING in ./~/react-country-region-selector/dist/rcrs.js
Critical dependencies:
1:477-484 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-country-region-selector/dist/rcrs.js 1:477-484

**Comment by benkeen** [comment]
Ack, sorry @mukraskazungu, I forgot about this one - will look at tonight.

**Comment by benkeen** [comment]
Hi @mukraskazungu, so I looked at this and it's actually working as intended. How are you including the rcrs.js file in your application? If you're using es6 modules, I'm curious if importing `src/rcrs.js` directly rather than the dist file fixes the problem for you.

**Comment by mukraskazungu** [comment]
Thank you.I will check it
