### ISSUE TITLE
Incorrect region code for Hakkaio, JP

### ISSUE THREAD

**Issue by hornetnz** [benkeen/country-region-selector#40]
My internationalization team alerted me to a region code issue:

Region code for "Hokkaido" is incorrect in Address. "Hokkaido" is one of the prefectures within Japan.
Currently, "Hokkaido" region code defaults to "04". However, the correct "Hokkaido" region code is "01". "04" is Miyagi.

**Comment by benkeen** [comment]
Thanks @hornetnz, I'll fix this up.

**Comment by benkeen** [comment]
I'll update it according to this wikipedia article: https://simple.wikipedia.org/wiki/Prefectures_of_Japan

**Comment by benkeen** [comment]
Hi @hornetnz - this has been fixed in 0.3.5. Thank your i18n team for me for spotting this!

**Comment by ellenhutchings** [comment]
According to https://www.iso.org/obp/ui/#iso:code:3166:JP, the codes matches the 3166-2 standard before. I don't know where that wikipedia page got its data from, but since it claims to be the ISO, I think the page is wrong.

**Comment by benkeen** [comment]
Uh-oh. Wikipedia fail? Sometimes the iso specs are out of date though.

@hornetnz - you wouldn't mind touching base with your team and checking this?

**Comment by benkeen** [comment]
Actually - what's in that iso.org link looks consistency with what @hornetnz said it should have been - and with what the original values were set to, as you noted @ellenhutchings. 

Looks like the ISO link is correct and up to date. I'm going to revert it back to the original values (I'll check them all over when I do so). 

Sorry for the fuss, Ellen, and thanks for catching it.

**Comment by hornetnz** [comment]
Not sure I understand...was the fix in 0.3.5 incorrect?

**Comment by benkeen** [comment]
Yeah, looks like that Wikipedia page I was using was incorrect. That ISO page linked above shows the correct data. You mentioned `Currently, "Hokkaido" region code defaults to "04". However, the correct "Hokkaido" region code is "01". "04" is Miyagi.` - looking at the original settings for Japan, that data looked correct.

No big deal, I'll fix this up tonight!

**Comment by hornetnz** [comment]
Maybe Im looking at it wrong, but the wiki and ISO both show Hokkaido as 01...?

**Comment by ellenhutchings** [comment]
I swear when I looked at them yesterday they were different. But today @hornetnz is right, Mea culpa.

**Comment by hornetnz** [comment]
Ok good, I'm not crazy! :)

**Comment by benkeen** [comment]
Well apparently I am! I'd also have sworn something was off. :) Thanks @hornetnz. Closing.
