### ISSUE TITLE
Dynamic trigger

### ISSUE THREAD

**Issue by brandonros** [benkeen/country-region-selector#5]
How would one trigger the initialization function of country-region-selector on dynamically loaded content?

**Comment by benkeen** [comment]
Good point, @brandonros! It's not currently available - I didn't anticipate that. I'll add this feature tonight. Right now the code is entirely namespaced; I'll need to expose a `window.crs` + wrap it in UMD format.

**Comment by brandonros** [comment]
@benkeen, could you also make the region dropdown obey the data-value="2-char" attribute? Otherwise, I won't be able to use your library in my project.

**Comment by brandonros** [comment]
I was able to hack the issue I had by naming the initiation function and calling it when the dynamic content was loaded.

**Comment by benkeen** [comment]
I just released 0.1.4 to allow people to re-initialize country-region dropdowns in dynamically inserted page content. 

> could you also make the region dropdown obey the data-value="2-char" attribute? Otherwise, I won't be able to use your library in my project.

Sorry, but unfortunately not. The reason is that not all regions from different countries can be reduced to 2 characters.
