### ISSUE TITLE
Example 6 & 7 show wrong regions for selected country

### ISSUE THREAD

**Issue by gricey432** [benkeen/country-region-selector#50]
Was just checking this library out and noticed an issue with the example, not sure if it's a bug in the library or just in the example.

http://benkeen.github.io/country-region-selector/ Example 6 shows the wrong regions for the listed countries.

![screenshot_2017-07-05_13-23-21](https://user-images.githubusercontent.com/1611345/27848008-303820de-6185-11e7-9dd1-3b686b9c2325.png)

**Comment by benkeen** [comment]
Hmm, thanks @gricey432! Looks fishy. I'll check it out.

**Comment by gricey432** [comment]
Looks like example 7 does the same thing

**Comment by benkeen** [comment]
Yeah. I tinkered with it last night and it was working fine locally. Odd - I'll investigate this weekend. Thanks very much for letting me know, it may well be a bug.

**Comment by ellenhutchings** [comment]
I just checked it out and this is definitely happening for me too. I noticed that I got _different_ incorrect regions when I switched from United States to Canada. I think the id or whatever field that's being checked to populate the regions to be populated is being messed up somehow.

**Comment by benkeen** [comment]
Sorry for the wait on this. I see the problem now. Multiple fields on the same page all share the same country source, so targeting index N on a field with whitelisted/blacklisted items won't always target the appropriate country. Let me see what I can do...

**Comment by benkeen** [comment]
Almost there! I've made a patch, but I need to make it more performant. If I don't get it out tonight I should get a new version done by tomorrow night.
