### ISSUE TITLE
Missing region - Tokyo, Japan

### ISSUE THREAD

**Issue by brentlblair** [benkeen/country-region-selector#61]
It seems that Tokyo, Japan is missing from the latest version.
|Tochigi~09|Tokushima~36|Saga~41|Totigi~09|

**Comment by benkeen** [comment]
Thanks @brentlblair  - it was using an old version of [country-region-data](https://github.com/benkeen/country-region-data). I'll release a new version shortly.

**Comment by benkeen** [comment]
All fixed. This has been updated in 1.4.1. Thanks again! 
http://benkeen.github.io/country-region-selector/
