### ISSUE TITLE
Feature Request: Define "preferred" countries that show up first in dropdown

### ISSUE THREAD

**Issue by pjatx** [benkeen/country-region-selector#62]
As a user living in a certain country, I might want that country to be at the top of the dropdown so I don't have to scroll the entire alphabetical list to choose it. 

As an ecommerce store manager, this might also help abandoment rates. 

Maybe you could specify a list of countries you'd want to show up first?

**Comment by benkeen** [comment]
That's an absolutely terrific idea. I'd like that feature myself. I'll add this as soon as I can get a little time. 

Thanks!

**Comment by pjatx** [comment]
Awesome, thanks! Great library btw - was so easy to use and works great!

**Comment by benkeen** [comment]
Thanks again @pjatx - I just released 0.5.0 that includes this feature. 
https://github.com/benkeen/country-region-selector/releases/tag/0.5.0
