### ISSUE TITLE
Regions do not update properly

### ISSUE THREAD

**Issue by Webberjo** [benkeen/country-region-selector#68]
If I rearrange the country select to have Canada and United States at the top of the list and then select Canada, the region select is populated with Afghanistan regions. This likely means the region select is populated based on selected country index instead of value.
```js
let countries = document.getElementById('country');
let canada = countries.options[40];
let united_states = countries.options[235];
countries.remove(40);
countries.remove(235);
countries.add(canada, 1);
countries.add(united_states, 2);
```

**Comment by benkeen** [comment]
Hey @Webberjo, yeah - doing something like may well cause problems. I think that yes, the internal code relies on index (which is nice and fast). The next version will include `data-preferred="US,CA,MX"` and `data-preferred-delim="-----"` options to shift specific countries to the top. I'll try to get that going today.

**Comment by benkeen** [comment]
Added in 0.5.0: https://github.com/benkeen/country-region-selector/releases/tag/0.5.0

Thanks!
