### ISSUE TITLE
United Kingdom regions corrupted

### ISSUE THREAD

**Issue by sventech** [benkeen/country-region-selector#7]
I'm not sure what happened, but the list of regions of the UK/GB is corrupted. Several county names are cut off or mangled in some way. I traced all the way to the first commit, and they are still wrong. I found a few correct versions, but it looks like a find and replace messed it up. If you still have your original source, perhaps you can correct it. Otherwise I'll try to track down the [correct](http://en.wikipedia.org/wiki/List_of_postcode_districts_in_the_United_Kingdom) [values](http://en.wikipedia.org/wiki/Postal_counties_of_the_United_Kingdom) to use.

**Comment by benkeen** [comment]
Huh! Thanks, @sventech - I should have a little time later today. I'll take a look and patch them up.

**Comment by benkeen** [comment]
I think perhaps this list may be best to use: http://en.wikipedia.org/wiki/List_of_counties_of_the_United_Kingdom

It's a list of all counties, not postcodes / districts.

**Comment by sventech** [comment]
UK subdivisions are confusing. It seems like since the postal counties  have been deprecated in favor of the locality prefix in the postal code, it might be appropriate to just use England, Northern Ireland, Scotland and Wales, plus all the crown territories, etc. Zippopotam.us postal code API just returns country names as region info.

**Comment by benkeen** [comment]
Yeah very confusing, agreed. But counties are definitely still used so I think they're what most people would want and expect to see when selecting the UK country (I lived there until I was 16). What I think I'll do is use the ones that haven't been dropped, erring on the side of caution.

Good call on the crown territories. I think that might lend itself to a separate country - UK Crown Territories or something.

**Comment by sventech** [comment]
Wow! Yesterday I read up on citizenship status of people in the [`UK Overseas Territories`](http://en.wikipedia.org/wiki/United_Kingdom_Overseas_Territories_Association) (the current official term) and I'm quite amazed at the complexity of their status, although nothing surprises me anymore, since I recently learned how 5 million American citizens (in various territories) with no criminal record can't vote in presidential elections because the supreme court said they're from "alien races". :-(

Anyway, I agree that the counties are the appropriate thing since that is what goes on addresses, etc. I'm also interested in the regional abbreviations in the other issue, and I believe there are postal code prefixes that correspond to the postal counties / cities.

**Comment by benkeen** [comment]
Great - thanks for that link. Super handy. I'm just about to commit the latest version - give me a few mins.

**Comment by benkeen** [comment]
Heya, all fixed. I just released 0.1.7 with the latest code. See demo:
http://benkeen.github.io/country-region-selector/
